### PR TITLE
ItemId-370076129 Changes to implement UserStory7

### PR DESCRIPTION
**Pull request by rseera**
Hi, Please review the changes and comment accordingly

### CODE REVIEW

**Review by bkasireddy — COMMENTED** [review]
Hi Rseera, 

Code is not aligned properly so have a look and format it accordingly.

**Comment by rseera** [comment]
> Hi Rseera,
> 
> Code is not aligned properly so have a look and format it accordingly.

**Comment by rseera** [comment]
Ok, I will check the formatting.

**Comment by bkasireddy** [comment]
@bkasireddy File formatted now so can you check

**Review by rseera — COMMENTED** [review]
Formatting looks good

**Review by bkasireddy — APPROVED** [review]
all good.

**Pull request merged**
